# Generated by Django 3.0.5 on 2022-04-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='parent_email',
            field=models.EmailField(default='default_parent@gmail.com', max_length=50),
        ),
    ]
