# Generated by Django 3.0.5 on 2022-04-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_students_parent_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationStaffs',
        ),
    ]
