# Generated by Django 3.0.7 on 2022-04-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_delete_notificationstaffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackstudent',
            name='anonyms',
            field=models.BooleanField(default=False),
        ),
    ]
