# Generated by Django 3.0.7 on 2022-04-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_feedbackstudent_anonyms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackstudent',
            old_name='anonyms',
            new_name='anonymous',
        ),
    ]
